name: EPG Cronjobs

on:
  schedule:
    - cron: '30 0 * * *'   # 00:30 UTC = 02:30 CEST

jobs:
  epg-generate:
    runs-on: ubuntu-latest
    steps:
      - name: EPG generieren
        run: curl -sL "http://mrxsh.atwebpages.com/epg/epg.php" --max-time 300
